import React from 'react'

export const About = () => {
    return (
        <div>
            This is the about component.
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus deleniti nemo, vel quaerat iure sapiente blanditiis fuga impedit sint ea. Atque repellendus neque illum exercitationem. Fugit sequi veritatis reiciendis! Ea quod dicta consequatur culpa, saepe nulla. Minima quibusdam impedit illum et ea obcaecati dolorem nisi cum laborum? Ipsa ex nisi voluptatibus vitae ullam minima hic inventore saepe maxime atque, illum quae accusantium dolores assumenda delectus distinctio repellat aut. Blanditiis reprehenderit id molestiae repellat illo at, excepturi tenetur quae possimus porro, vitae distinctio iure. Asperiores excepturi, dicta veniam voluptate nisi nulla enim necessitatibus dolorum officiis doloremque optio sapiente fuga, harum facere? In, ex veritatis, sunt laboriosam tempora fuga officia illo incidunt nemo sequi reiciendis ducimus a eos. Nisi animi veritatis dolorem itaque ullam natus magni et quasi molestias quibusdam. Nisi voluptates sint sapiente officiis dolorem at animi, aliquid possimus expedita maxime distinctio nihil error qui voluptatum. Molestiae quidem consectetur reprehenderit expedita rerum eligendi quas obcaecati. Beatae, exercitationem non quidem cum sequi odio quos dolorem, vero dicta asperiores atque! Natus sapiente molestias sequi ex, recusandae id minima deserunt minus neque libero quasi rem deleniti, quidem nostrum culpa. Aliquid deserunt nisi laudantium doloribus placeat reprehenderit adipisci ducimus iste pariatur nam autem provident debitis impedit veritatis a dicta, voluptatibus saepe id dolorem incidunt officia, ea ipsam. Expedita vel repellendus illo sunt sapiente cupiditate suscipit quo laboriosam distinctio nulla? Neque placeat aperiam harum odit, est modi nisi corporis dolor quae iste eius quo, praesentium ipsa distinctio accusantium at sit enim officia eum beatae illum doloribus ut minima. Ipsum sequi laborum reiciendis maxime dolorem tempore ullam distinctio illo, amet earum aperiam consequuntur labore obcaecati atque nobis quaerat ea? Magni molestiae aliquam ab inventore perferendis ratione fugit excepturi, iusto deleniti facere, non quibusdam nulla harum, repudiandae autem magnam maxime amet dicta aperiam libero. Ea, non sequi beatae debitis quis exercitationem deleniti quas, officiis modi cumque, nihil molestiae ullam quasi maxime perspiciatis. Quidem dolor, quasi veniam animi architecto hic rerum rem deleniti esse accusamus ad eum eligendi tenetur. Ullam, nemo maxime nostrum rem quo alias praesentium reiciendis autem?</p>
        </div>
    )
}
